CREATE TABLE EMPLOYEE (
EID INTEGER PRIMARY KEY,
ENAME VARCHAR2(100) NOT NULL,
EPOSITION VARCHAR2(100),
EUSERNAME VARCHAR2(20),
EPASSWORD VARCHAR2(20),
MANAGERID INTEGER,
CONSTRAINT Unique_Username UNIQUE (EUSERNAME)
);

CREATE TABLE REIMBURSEMENT (
RID INTEGER PRIMARY KEY,
AMOUNT NUMBER,
RDESCRIPTION VARCHAR(200),
EID INTEGER,
FOREIGN KEY (EID) REFERENCES EMPLOYEE(EID)
);

INSERT INTO EMPLOYEE VALUES (1,'Bob Thornton','CEO','bobthorn','Dallas86',1);
INSERT INTO EMPLOYEE VALUES (2,'Dave Stevens','Sales','dvdst','salesrox',1);
INSERT INTO EMPLOYEE VALUES (3,'Larry Thomas','Marketing','larryth','osu89',1);
INSERT INTO EMPLOYEE VALUES (4,'Bill Sampson','Sales','bills','password',1);
INSERT INTO EMPLOYEE VALUES (5,'test','test','test','test',0);

CREATE SEQUENCE REIM_REQ_IDS
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE PROCEDURE
REIMBURSEREQUEST(EMP IN INTEGER, AMT IN NUMBER, DES IN VARCHAR2) AS
BEGIN
    INSERT INTO REIMBURSEMENT (RID, AMOUNT, RDESCRIPTION, EID)
    VALUES(REIM_REQ_IDS.NEXTVAL, AMT, DES, EMP);
END;
/
CREATE OR REPLACE PROCEDURE
MANAGERVIEW(MID IN INTEGER, S OUT SYS_REFCURSOR) AS
BEGIN
    OPEN S FOR
    SELECT *
    FROM REIMBURSEMENT
    WHERE REIMBURSEMENT.EID IN (
        SELECT EID
        FROM EMPLOYEE
        WHERE EMPLOYEE.MANAGERID = MID
        );
END;
/

COMMIT;
    


